---
- name: Mettre à jour les paquets
  ansible.builtin.package:
    name: "*"
    state: latest
  when: ansible_os_family in ["Debian", "RedHat"]

- name: Installer Git
  ansible.builtin.package:
    name: git
    state: present

- name: Installer Node.js (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  block:
    - name: Ajouter le dépôt NodeSource
      ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_{{ node_version }} | bash -
      args:
        executable: /bin/bash

    - name: Installer Node.js
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: yes

- name: Installer Node.js (RedHat/Rocky)
  when: ansible_os_family == "RedHat"
  block:
    - name: Ajouter le dépôt NodeSource
      ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_{{ node_version }} | bash -
      args:
        executable: /bin/bash

    - name: Installer Node.js
      ansible.builtin.yum:
        name: nodejs
        state: present

- name: Cloner l’application quiz-ansible
  ansible.builtin.git:
    repo: "{{ app_repo }}"
    dest: "{{ app_dest }}"
    version: HEAD
    force: yes

- name: Installer les dépendances avec npm
  ansible.builtin.shell: npm install
  args:
    chdir: "{{ app_dest }}"

- name: Builder le projet
  ansible.builtin.shell: npm run build
  args:
    chdir: "{{ app_dest }}"

- name: Installer serve globalement
  ansible.builtin.shell: npm install -g serve

- name: Lancer l’application avec serve
  ansible.builtin.shell: nohup serve -s dist > /dev/null 2>&1 &
  args:
    chdir: "{{ app_dest }}"
